name: HACS action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate with HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS - Integration
        uses: hacs/action@main
        with:
          category: integration

      - name: HACS - Plugin
        uses: hacs/action@main
        with:
          category: plugin
